# Generated by Django 4.2.2 on 2023-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_billdata_ceb_remove_billdata_nwsdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('meter_readings', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NWSDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('meter_readings', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BillData',
        ),
    ]
