# Generated by Django 4.2.2 on 2023-06-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ceb_nwsdb_delete_billdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceb',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
