# Generated by Django 4.2.2 on 2023-06-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ceb_meter_readings_alter_ceb_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceb',
            name='meter_readings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ceb',
            name='units',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='nwsdb',
            name='meter_readings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='nwsdb',
            name='units',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='nwsdb',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
