# Generated by Django 4.2.2 on 2023-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ceb_meter_readings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceb',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nwsdb',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
