# Generated by Django 4.2.2 on 2023-07-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ceb_created_nwsdb_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceb',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nwsdb',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
